---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  remote_user: snwbr
  become: yes
  gather_facts: yes
  
  roles:
  - role: common

- hosts: mongo_servers
  become: yes
  roles:
  - role: mongod